" .vimrc
"
" Maintained by iltaek <iltaekkwon@gmail.com>
" forked from posquit0@github (Claud D. Park)
"

let $VIM_HOME=$HOME.'/.vim'

"
" Installation vim-plug
" If it already installed, this does nothing
"
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source ~/.vimrc
endif

""" General configuration
if filereadable(expand("$VIM_HOME/general.vim"))
	source $VIM_HOME/general.vim
endif
if filereadable(expand("$VIM_HOME/visual.vim"))
	source $VIM_HOME/visual.vim
endif

""" Plugin configuration
"   All plugins are managed by 'vim-plug (by junegunn)'
"   List & config of the plugins are separated to several files like
"   'plugins.NAME.vim'
if filereadable(expand("$VIM_HOME/plugins.vim"))
	source $VIM_HOME/plugins.vim
endif

""" Theme configuration
if filereadable(expand("$VIM_HOME/theme.vim"))
	source $VIM_HOME/theme.vim
endif

